# Generated by Django 2.1.5 on 2019-05-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datageeks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tilte',
            new_name='title',
        ),
    ]
